-- AlterTable
ALTER TABLE "DailyCell" ADD COLUMN     "source" TEXT NOT NULL DEFAULT 'calendar',
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "RatePrice" ADD COLUMN     "source" TEXT NOT NULL DEFAULT 'calendar',
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
