const products={link:{title:'Your distribution.<br>Under control.',copy:'Manage availability and rates across your channels from a single workspace. See what is connected and what needs attention.',label:'RevioLink / Availability calendar',name:'RevioLink',slug:'reviolink',detail:'Availability · Rates · Restrictions · Channels',accent:'#52d6e8'},crs:{title:'Your next reservation.<br>The bigger picture.',copy:'Bring reservations, rates and guest information together. Understand performance from the same records your team works with.',label:'RevioCRS / Performance overview',name:'RevioCRS',slug:'reviocrs',detail:'Reservations · Guests · Rate plans · Analytics',accent:'#aaa6ff'},pms:{title:'A better rhythm.<br>For every working day.',copy:'Connect your front desk, housekeeping and property operations. Give each team a clear view of the work in front of them.',label:'RevioPMS / Housekeeping',name:'RevioPMS',slug:'reviopms',detail:'Front desk · Housekeeping · Folios · Maintenance',accent:'#6de0b3'},direct:{title:'Your hotel.<br>Booked directly.',copy:'A guest-facing booking experience connected to your hotel’s availability, configured through RevioCRS.',label:'RevioDirect / Room selection',name:'RevioDirect',slug:'reviodirect',detail:'Room selection · Stay details · Hotel branding',accent:'#f0c893'}};
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');
const tabs=[...document.querySelectorAll('[role=tab]')];
function choose(id){const p=products[id];if(!p)return;tabs.forEach(t=>{const active=t.dataset.product===id;t.setAttribute('aria-selected',active);t.tabIndex=active?0:-1});document.querySelector('#product-panel').setAttribute('aria-labelledby','tab-'+id);document.querySelector('#product-title').innerHTML=p.title;document.querySelector('#product-copy').textContent=p.copy;document.querySelector('#product-link').textContent='Explore '+p.name+' ↗';document.querySelector('#product-link').href='https://reviosoft.app/'+p.slug;document.querySelector('#product-image').src='assets/'+id+'.png';document.querySelector('#product-image').alt=p.label;document.querySelector('#screen-label').textContent=p.label;document.querySelector('#product-detail').textContent=p.detail;document.querySelector('.product-section').style.setProperty('--accent',p.accent);const panel=document.querySelector('#product-panel');panel.classList.remove('switching');void panel.offsetWidth;panel.classList.add('switching');}
document.querySelectorAll('[data-product]').forEach(el=>el.addEventListener('click',()=>{choose(el.dataset.product);closeMega()}));
tabs.forEach((tab,i)=>tab.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight')next=(i+1)%tabs.length;if(e.key==='ArrowLeft')next=(i+tabs.length-1)%tabs.length;if(e.key==='Home')next=0;if(e.key==='End')next=tabs.length-1;if(next!==undefined){e.preventDefault();tabs[next].focus();choose(tabs[next].dataset.product)}}));
document.querySelectorAll('[data-frame]').forEach(btn=>btn.onclick=()=>{document.body.classList.toggle('browser-frame',btn.dataset.frame==='browser');document.querySelectorAll('[data-frame]').forEach(b=>{b.classList.toggle('selected',b===btn);b.setAttribute('aria-pressed',b===btn)})});
const toggle=document.querySelector('#products-toggle'),mega=document.querySelector('#mega');
function closeMega(){mega.hidden=true;toggle.setAttribute('aria-expanded','false')}
toggle.onclick=()=>{mega.hidden=!mega.hidden;toggle.setAttribute('aria-expanded',!mega.hidden)};
document.addEventListener('click',e=>{if(!e.target.closest('header'))closeMega()});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMega();document.querySelector('header').classList.remove('menu-open');document.querySelector('#mobile-menu').setAttribute('aria-expanded','false');toggle.focus()}});
document.querySelector('#mobile-menu').onclick=e=>{const open=document.querySelector('header').classList.toggle('menu-open');e.currentTarget.setAttribute('aria-expanded',open);if(!open)closeMega()};
document.querySelectorAll('header a[href^="#"]').forEach(a=>a.addEventListener('click',()=>{document.querySelector('header').classList.remove('menu-open');document.querySelector('#mobile-menu').setAttribute('aria-expanded','false')}));
if('IntersectionObserver'in window){document.body.classList.add('js-motion');const reveal=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');reveal.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>reveal.observe(el));}
const steps=[...document.querySelectorAll('.story-step')];let timers=[];
function play(){timers.forEach(clearTimeout);const board=document.querySelector('.story-board');steps.forEach((s,i)=>s.classList.toggle('active',i===0||reduced.matches));board.classList.toggle('playing',!reduced.matches);document.querySelector('#play-story').innerHTML='Replay the workflow <span>↻</span>';if(reduced.matches)return;[1,2].forEach(i=>timers.push(setTimeout(()=>steps[i].classList.add('active'),i*1400)));timers.push(setTimeout(()=>board.classList.remove('playing'),4200));}
document.querySelector('#play-story').onclick=play;
if('IntersectionObserver'in window){const storyObserver=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){play();storyObserver.disconnect()}},{threshold:.65});storyObserver.observe(document.querySelector('.story-board'))}
reduced.addEventListener('change',()=>{if(reduced.matches){timers.forEach(clearTimeout);steps.forEach(s=>s.classList.add('active'));document.querySelector('.story-board').classList.remove('playing')}});
